import type { MCPClient } from './client.js';

export interface GitHubIssueParams {
  owner: string;
  repo: string;
  title: string;
  body: string;
  labels?: string[];
  taskId: string;
  agentId: string;
}

export interface GitHubIssueResult {
  number: number;
  html_url: string;
}

export async function createGitHubIssue(
  client: MCPClient,
  params: GitHubIssueParams
): Promise<GitHubIssueResult | null> {
  const body = [
    params.body,
    '',
    '---',
    `**Task ID**: ${params.taskId}`,
    `**Agent**: ${params.agentId}`,
    `**Created**: ${new Date().toISOString()}`,
    `*Generated by KingdomOS*`,
  ].join('\n');

  const result = await client.call<GitHubIssueResult>('github.issues.create', {
    owner: params.owner,
    repo: params.repo,
    title: params.title,
    body,
    labels: params.labels ?? ['kingdomos', 'auto-generated'],
  });

  if (!result.success) {
    return null;
  }

  return result.data ?? null;
}
