import type { MCPClient } from './client.js';

export interface GitHubPRParams {
  owner: string;
  repo: string;
  title: string;
  body: string;
  head: string;
  base: string;
  taskIds: string[];
  agentId: string;
  diff?: string;
}

export interface GitHubPRResult {
  number: number;
  html_url: string;
}

export async function createGitHubPR(
  client: MCPClient,
  params: GitHubPRParams
): Promise<GitHubPRResult | null> {
  const taskList = params.taskIds.map((id) => `- ${id}`).join('\n');
  const body = [
    params.body,
    '',
    '## Task References',
    taskList,
    '',
    '---',
    `**Agent**: ${params.agentId}`,
    `**Created**: ${new Date().toISOString()}`,
    `*Generated by KingdomOS*`,
  ].join('\n');

  const result = await client.call<GitHubPRResult>('github.pulls.create', {
    owner: params.owner,
    repo: params.repo,
    title: params.title,
    body,
    head: params.head,
    base: params.base,
  });

  if (!result.success) {
    return null;
  }

  return result.data ?? null;
}
